version: '3.7'

services:
  agent:
    image: blancopedro/rpi-temp-simple:latest
    volumes:
      - /sys:/sys:ro
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
      restart_policy:
        condition: any
