version: '3.7'

services:
  agent:
    image: busybox:latest
    volumes:
      - /sys:/sys:ro
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
      restart_policy:
        condition: any
    command: sh -c \"while true; do { echo -e \'HTTP/1.1 200 OK\\r\\n'; echo \'{\\\"cpu_temp\\\":\\\"$$(cat /sys/class/thermal/thermal_zone0/temp)\\\"}\'; } | nc -l -p 8080; done; exit\"
